### ISSUE TITLE
Hibernate 5 Module Not Ignoring hibernateLazyInitializer

### ISSUE THREAD

**Issue by EarthCitizen** [FasterXML/jackson-datatype-hibernate#143]
The Hibernate 5 Module should ignore `hibernateLazyInitializer` by default. Jackson is attempting to serialize this, and that results in an error:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.hateoas.EntityModel["content"]->some.package.Pojo$HibernateProxy$rGmV5ok5["hibernateLazyInitializer"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.12.4.jar:2.12.4]
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276) ~[jackson-databind-2.12.4.jar:2.12.4]
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400) ~[jackson-databind-2.12.4.jar:2.12.4]
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71) ~[jackson-databind-2.12.4.jar:2.12.4]
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33) ~[jackson-databind-2.12.4.jar:2.12.4]
```

**Comment by cowtowncoder** [comment]
Sounds like it might be relatively simple thing to do.

But one thing that would be super helpful for anyone trying to solve this would be a unit test to reproduce the issue. That'd also work as verification for solution.
