### ISSUE TITLE
Support for Hibernate Reactive

### ISSUE THREAD

**Issue by agreedSkiing** [FasterXML/jackson-datatype-hibernate#166]
# Missing support for [Hibernate Reactive](https://hibernate.org/reactive/) with Mutiny and Stage.

First of all, jackson-datatype-hibernate5 kind of work since Hibernate Reactive uses Hibernate ORM 5.6, so the deserialize works to a certain extent but fails as soon as the deserialize hits Hibernate Reactives Mutiny.fetch or Stage.

Included a log from the application where I encountered the error

```log
2022-12-29 09:28:07,488 INFO  [se.com.pro.com.ent.lis.AuditListener] (vert.x-eventloop-thread-0) {"Event":"UPDATE","Audit":{"PreUpdate":{
  "resourceIdentifier" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
  "createdAt" : "2022-11-14T12:37:44.284Z",
  "modifiedAt" : "2022-12-29T08:24:51.022140Z",
  "createdBy" : "Integration Test",
  "modifiedBy" : null,
  "version" : 2,
  "systemIdentifier" : "CS2",
  "systemType" : "SEARCH",
  "systemStatus" : "PENDING",
  "systemVersion" : "system_version",
  "name" : "lIpNTEk93ApQj4V10c4ecVFPnThU6may",
  "alternateName" : "alternate_name",
  "description" : "description",
  "maintainer" : "maintainer",
  "source" : "system_source",
  "codes" : [ {
    "resourceIdentifier" : "5f6e7636-f9f0-46f6-91c9-20ce9b384e3b",
    "createdAt" : "2022-11-14T12:37:44.284705Z",
    "modifiedAt" : null,
    "createdBy" : "Integration Test",
    "modifiedBy" : null,
    "version" : 0,
    "codeIdentifier" : "code_id_1",
    "displayName" : "display_name",
    "originalText" : "original_text",
    "additionalInfo" : "additional_info",
    "codeSystem" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
    "address" : null
  }, {
    "resourceIdentifier" : "a7f7f851-f56b-4aff-bd98-1c0a9638c99a",
    "createdAt" : "2022-11-14T12:37:44.284705Z",
    "modifiedAt" : null,
    "createdBy" : "Integration Test",
    "modifiedBy" : null,
    "version" : 0,
    "codeIdentifier" : "code_id_2",
    "displayName" : "display_name",
    "originalText" : "original_text",
    "additionalInfo" : "additional_info",
    "codeSystem" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
    "address" : null
  } ]
},"PostUpdate":{
  "resourceIdentifier" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
  "createdAt" : "2022-11-14T12:37:44.284Z",
  "modifiedAt" : "2022-12-29T08:28:07.481105600Z",
  "createdBy" : "Integration Test",
  "modifiedBy" : null,
  "version" : 3,
  "systemIdentifier" : "CS2",
  "systemType" : "SEARCH",
  "systemStatus" : "PENDING",
  "systemVersion" : "system_version",
  "name" : "LeHADiMWFAOVVLdOWtYKNgOWLNVNZUNy",
  "alternateName" : "alternate_name",
  "description" : "description",
  "maintainer" : "maintainer",
  "source" : "system_source",
  "codes" : [ {
    "resourceIdentifier" : "5f6e7636-f9f0-46f6-91c9-20ce9b384e3b",
    "createdAt" : "2022-11-14T12:37:44.284705Z",
    "modifiedAt" : null,
    "createdBy" : "Integration Test",
    "modifiedBy" : null,
    "version" : 0,
    "codeIdentifier" : "code_id_1",
    "displayName" : "display_name",
    "originalText" : "original_text",
    "additionalInfo" : "additional_info",
    "codeSystem" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
    "address" : null
  }, {
    "resourceIdentifier" : "a7f7f851-f56b-4aff-bd98-1c0a9638c99a",
    "createdAt" : "2022-11-14T12:37:44.284705Z",
    "modifiedAt" : null,
    "createdBy" : "Integration Test",
    "modifiedBy" : null,
    "version" : 0,
    "codeIdentifier" : "code_id_2",
    "displayName" : "display_name",
    "originalText" : "original_text",
    "additionalInfo" : "additional_info",
    "codeSystem" : "39eabf3d-2ab1-4b39-bf79-ec57747ea36e",
    "address" : null
  } ]
}}}

2022-12-29 09:28:07,501 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-0) Request failed: com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: se.company.pro.codesystem.db.entity.Code.address, could not initialize proxy - no Session (through reference chain: se.company.pro.codesystem.db.entity.CodeSystem["codes"]->org.hibernate.collection.internal.PersistentSet[0]->se.company.pro.codesystem.db.entity.Code["address"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:684)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:171)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:684)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:171)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
        at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.BasicServerJacksonMessageBodyWriter.writeResponse(BasicServerJacksonMessageBodyWriter.java:39)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:220)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:191)
        at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:120)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: se.company.pro.codesystem.db.entity.Code.address, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:614)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
        at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162)
        at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:168)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:97)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        ... 34 more
```

**Comment by agreedSkiing** [comment]
The fault lies with quarkus-resteasy-reactive-jackson not including 'jackson-datatype-hibernate5'

**Comment by cowtowncoder** [comment]
Glad you were able to figure it out @agreedSkiing !
