### ISSUE TITLE
jackson-datatype-hibernate5 is compiled against obsolete version of hibernate

### ISSUE THREAD

**Issue by tsachev** [FasterXML/jackson-datatype-hibernate#79]
hibernate5 module is compiled against 5.0.0.Beta2 which is too old.
The main  problem is that before hibernate was released the `Session` api changed. https://github.com/hibernate/hibernate-orm/commit/7c006f7fcd2258d5253dc9e573aaa433201572ae

And now I get 
```
java.lang.NoSuchMethodError: org.hibernate.Session.close()Ljava/sql/Connection;
	at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.initializeCollection(PersistentCollectionSerializer.java:204)
	at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.findLazyValue(PersistentCollectionSerializer.java:159)
	at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.serialize(PersistentCollectionSerializer.java:115)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanSerializer.serialize(UnwrappingBeanSerializer.java:120)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:973)
```
When I create my hibernate5 module with session factory.

5.0.0.CR1 is the first version with current api, if you need for some reason to use unofficial version.

**Comment by cowtowncoder** [comment]
@tsachev Thank you for reporting this. I assume older version was the most recent at the time when hibernate5 support for added.

**Comment by cowtowncoder** [comment]
Ouch. I thought I had fixed this for 2.7.0-rc2, but does not look like that went through for some reason. Will update for next release candidate (or 2.7.0 final)

**Comment by cowtowncoder** [comment]
Hmmh. Lovely. Tests pass with 5.0.0.Final, fail with 5.0.5.Final. Need to see why....

**Comment by tsachev** [comment]
meanwhile 5.0.6 is out, make sure to also check against it.
