### ISSUE TITLE
ClassNotFoundException using jackson-datatype-hibernate5 2.7.1 with Hibernate 5.1.0.Final

### ISSUE THREAD

**Issue by rgoldberg** [FasterXML/jackson-datatype-hibernate#87]
ClassNotFoundException when using jackson-datatype-hibernate5 2.7.1 with Hibernate 5.1.0.Final.

```
java.lang.ClassNotFoundException: org.hibernate.bytecode.internal.javassist.FieldHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	at com.fasterxml.jackson.datatype.hibernate5.HibernateAnnotationIntrospector.isIgnorableType(HibernateAnnotationIntrospector.java:82)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.isIgnorableType(AnnotationIntrospectorPair.java:150)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.isIgnorableType(BeanDeserializerFactory.java:827)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:597)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:487)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:228)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1856)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:659)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:679)
```

**Comment by cyberaleks** [comment]
+1. Same issue

**Comment by cowtowncoder** [comment]
Dup of #86, fixed for 2.7.2.

**Comment by logemann** [comment]
Hmmm. Get the same error with 2.8.2. Do i missing artifacts? These are my relevant jars in CP:

jackson-annotations-2.8.2.jar
jackson-core-2.8.2.jar
jackson-databind-2.8.2.jar
jackson-datatype-hibernate4-2.8.2.jar
hibernate-core-5.2.2.Final.jar

**Comment by cowtowncoder** [comment]
@logemann Right, you must use `jackson-datatype-hibernate5` with Hibernate 5.x and not `jackson-datatype-hibernate4`. So that's the first part to fix.

But there may be other issues wrt Hibernate 5.x, see #92.
