### ISSUE TITLE
Collection initialization error using Hibernate 5.2.3 version

### ISSUE THREAD

**Issue by yoely** [FasterXML/jackson-datatype-hibernate#99]
Given the Scenario: A customer having list of lazy load addresses.
On Create customer (+ address) API, the response serialization is failed with the following error:

Caused by: java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionImplementor.getTransactionCoordinator()Lorg/hibernate/resource/transaction/TransactionCoordinator;
    at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.initializeCollection(PersistentCollectionSerializer.java:343)
    at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.findLazyValue(PersistentCollectionSerializer.java:313)
    at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.serialize(PersistentCollectionSerializer.java:252)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1419)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:940)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:618)

thanks,
Yoel

**Comment by yoely** [comment]
I had to implement few changes to have a temporary fix.
The root cause is Hibernate 5.2 change by merging hibernate-entitymanager into hibernate-core.
1. exclude import of hibernate-entitymanager artifact, by:
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.hibernate</groupId>
                    <artifactId>hibernate-entitymanager</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

2. few changes in jackson-datatype-hibernate5 artifact, I'm not sure about this fix, because few jackson  tests were failed but my applicative tests passed successfully. any comments about the following proposed solution?
2.1 in pom.xml
2.2.1 Set hibernate version to: 5.2.3 (originally version sets to 5.1.0)
2.2.2 remove dependency on hibernate-entity-manager artifact
2.2 edit HibernateProxySerializer.java, line: 186
to: 
final SharedSessionContractImplementor session = init.getSession();

**Comment by cowtowncoder** [comment]
As per #100 hopefully fixed now.
